/* Copyright (c) 2021-present Tomra Systems ASA */
/* Generated by facebook/create-react-app and subsequently modified */

import React, { Component } from 'react';
import FeatureHolder from "./FeatureHolder";
import './App.css';

class App extends Component {
  render() {

    return (
      <div className="App">
        <FeatureHolder/>
      </div>
    );
  }
}

export default App;
